### PR TITLE
learning pod 5: Weibo

### PR DESCRIPTION
**Pull request by chloelyh**
@pudding34 @chloelyh @keitakahashi338 @jiaxinchen27

### CODE REVIEW

**Comment by cmadland** [comment]
@pudding34 there were some problems with this PR. Please set up a meeting with me and your learning pod to go over the intended workflow.

**Comment by pudding34** [comment]
> @pudding34 there were some problems with this PR. Please set up a meeting with me and your learning pod to go over the intended workflow.

@cmadland No problem, our group will look for you when we have confirmed the meeting time.

**Comment by pudding34** [comment]
@cmadland  What time are you available on Monday?

**Comment by cmadland** [comment]
If you log into the course in Brightspace, there is a link to book a meeting. That link is connected to my calendar, so you don't have to worry about whether I'm available or not. Just pick a time.

**Pull request closed without merging**
