### PR TITLE
Code of Conduct

### PR DESCRIPTION
**Pull request by cmadland**
PR to create Code of Conduct for the class.

### CODE REVIEW

**Review by thildebrand — APPROVED** [review]

**Review by emilylehoux — APPROVED** [review]
I agree with these points. I have nothing to change or add as it seems pretty well done in my opinion. I will say, I wish every class had the same awareness and accountability as you implement In your courses. other professors need to learn this a bit better.

**Review by shaafijahangir — APPROVED** [review]
We, as a group, approve this code of conduct and have no concerns regarding to it. Thanks.

**Comment by Yifei10** [comment]
I as a reviewer of our group agree with these points.

**Review by Yifei10 — COMMENTED** [review]
I agree with these points

**Comment by Wenzhuozhang338** [comment]
I agree with these points as a reviewer.

**Pull request merged**
